name: Release

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  pull-requests: write
  id-token: write

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - name: Install
        run: npm ci

      - name: Create Release Pull Request or Publish
        uses: changesets/action@ae32849d5ba541f9ae29e40e22a623bc13562f51 # v2.1.2
        with:
          version-script: npm run version
          publish-script: npm run release
          commit-message: "chore: バージョン更新"
          pr-title: "chore: バージョン更新"
